server2MVC/server2MVC/Controllers/AdvertismnetsController.cs
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Drawing.Imaging;
    using System.Linq;
    using System.Threading.Tasks;
    using Grpc.Core;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations.Internal;
using server2MVC.Data;
    using server2MVC.Migrations;
    using server2MVC.Models;

    namespace server2MVC.Controllers
    {
        public class AdvertismnetsController : Controller
        {
            private readonly server2MVCContext _context;

            public AdvertismnetsController(server2MVCContext context)
            {
                _context = context;
            }



        public async Task<IActionResult> Advertiements(string category)
        {
            ViewBag.IsLoggedIn = !string.IsNullOrEmpty(HttpContext.Session.GetString("Id"));
            if (_context.Advertismnet != null)
            {
                var advertisementsQuery = _context.Advertismnet.AsQueryable();

                if (!string.IsNullOrEmpty(category))
                {
                    advertisementsQuery = advertisementsQuery.Where(a => a.category == category);
                }

                var advertisements = await advertisementsQuery
                    .Where(a => a.isActive)
                    .ToListAsync();

                ViewBag.Categories = new List<string> { "Біжутерія", "Одяг", "Електроніка", "Документи" };
                ViewBag.CurrentCategory = category;
                return View(advertisements);
            }
            else
            {
                return Problem("Entity set 'server2MVCContext.Advertismnet' is null.");
            }
        }





        // GET: Advertismnets
        public async Task<IActionResult> Index()
            {
                  return _context.Advertismnet != null ? 
                              View(await _context.Advertismnet.ToListAsync()) :
                              Problem("Entity set 'server2MVCContext.Advertismnet'  is null.");
            }

            // GET: Advertismnets/Details/5
            public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.Advertismnet == null)
                {
                    return NotFound();
                }

                var advertismnet = await _context.Advertismnet
                    .FirstOrDefaultAsync(m => m.ID == id);
                if (advertismnet == null)
                {
                    return NotFound();
                }

                return View(advertismnet);
            }

            // GET: Advertismnets/Create
            public IActionResult Create()
            {
                var userId = HttpContext.Session.GetString("Id");
                if (userId == null)
                {
                    return RedirectToAction("Login","Users");
                }
                return View();
            }
            public async Task<IActionResult> MyAdvertisements()
            {
                var userId = HttpContext.Session.GetString("Id");
                if (userId == null)
                {
                    return RedirectToAction("Login", "Users");
                }

            var user = await _context.User.FindAsync(int.Parse(userId));
            var userAdvertisements = await _context.Advertismnet
                .Where(a => a.CreateUserId == user.ID)
                .ToListAsync();

            var viewModel = new UserDashboardViewModel
            {
                User = user,
                Advertisements = userAdvertisements
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Advertismnet advertismnet, IFormFile ImageFile, User user, CategoryClassifier categoryClassifier)

        {
            var userId = HttpContext.Session.GetString("Id");
            if (userId == null)
            {
                Console.WriteLine("User ID is null in session.");
            }
            else
            {
                Console.WriteLine($"User ID from session: {userId}");
            }

            if (userId != null)
            {
                advertismnet.CreateUserId = int.Parse(userId);
            }
            else
            {
                advertismnet.CreateUserId = -1;
            }
            if (ImageFile != null) // Add null check here
            {
                string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                string extension = Path.GetExtension(ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                advertismnet.ImagePath = "~/Image/" + fileName;
                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Image", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
            }
            var titleWords = advertismnet.Title.Split(new[] { ' ', ',', '.', '!', '?' }, StringSplitOptions.RemoveEmptyEntries).ToList();
            var descriptionWords = advertismnet.Description.Split(new[] { ' ', ',', '.', '!', '?' }, StringSplitOptions.RemoveEmptyEntries).ToList();
            advertismnet.category = CategoryClassifier.Category(titleWords, descriptionWords);

            Random rnd = new Random();
            int randomId = rnd.Next(100000, 999999); // Мінімальне та максимальне значення для рандомного ідентифікатора
            advertismnet.UnicalId = randomId.ToString();


            _context.Add(advertismnet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Advertiements));


            return View(advertismnet);
        
    }











        // GET: Advertismnets/Edit/5
        // GET: Advertismnets/Edit/5
        // GET: Advertismnets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Advertismnet == null)
            {
                return NotFound();
            }

            var advertismnet = await _context.Advertismnet.FindAsync(id);
            if (advertismnet == null)
            {
                return NotFound();
            }

            return View(advertismnet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, bool isActive)
        {
            var advertismnet = await _context.Advertismnet.FindAsync(id);
            if (advertismnet == null)
            {
                return NotFound();
            }

            advertismnet.isActive = isActive;
            _context.Update(advertismnet);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool AdvertismnetExists(int id)
        {
            return (_context.Advertismnet?.Any(e => e.ID == id)).GetValueOrDefault();
        }















        // GET: Advertismnets/Delete/5
        public async Task<IActionResult> Delete(int? id)
            {
                var userId = HttpContext.Session.GetString("Id");
                if (userId == null)
                {
                    return RedirectToAction("Create");
                }
                if (id == null || _context.Advertismnet == null)
                {
                    return NotFound();
                }

                var advertismnet = await _context.Advertismnet
                    .FirstOrDefaultAsync(m => m.ID == id);
                if (advertismnet == null)
                {
                    return NotFound();
                }

                return View(advertismnet);
            }

            // POST: Advertismnets/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.Advertismnet == null)
                {
                    return Problem("Entity set 'server2MVCContext.Advertismnet'  is null.");
                }
                var advertismnet = await _context.Advertismnet.FindAsync(id);
                if (advertismnet != null)
                {
                    _context.Advertismnet.Remove(advertismnet);
                }
            
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            
        }
    }

server2MVC/server2MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using server2MVC.Data;
using server2MVC.Migrations;
using server2MVC.Models;
using System.Diagnostics;

namespace server2MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly server2MVCContext _context;
        public HomeController(server2MVCContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> IndexAsync(Advertismnet advertismnet)
        {
            ViewBag.IsLoggedIn = !string.IsNullOrEmpty(HttpContext.Session.GetString("Id"));
            
            if (_context.Advertismnet != null)
            {
               
                    
                

                
                var activeAdvertisements = await _context.Advertismnet
                    .Where(a => a.isActive)
                    .ToListAsync();
                return View(activeAdvertisements);
            }
            else
            {
                return Problem("Entity set 'server2MVCContext.Advertismnet'  is null.");
            }

        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

server2MVC/server2MVC/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using server2MVC.Data;
using server2MVC.Models;
using Microsoft.AspNetCore.Identity;
using System.Drawing.Text;

using Microsoft.AspNetCore;
using Microsoft.Extensions.Configuration.UserSecrets;

namespace server2MVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly server2MVCContext _context;

        public UsersController(server2MVCContext context)
        {
            _context = context;
        }
        /*public IActionResult DashBoard(User user)
        {
            var userId = HttpContext.Session.GetString("Id");
            if (userId == null)
            {
                return RedirectToAction("Login");
            }
            return View(user);
        }*/
        
        public IActionResult DashBoard()
        {
            var userId = HttpContext.Session.GetString("Id");
            if (userId == null)
            {
                return RedirectToAction("Login");
            }

            var user = _context.User.Find(int.Parse(userId));
            if (user == null)
            {
                return NotFound();
            }

            var userAdvertisements = _context.Advertismnet
                .Where(a => a.CreateUserId == int.Parse(userId))
                .ToList();

            var viewModel = new UserDashboardViewModel
            {
                User = user,
                Advertisements = userAdvertisements
            };

            return View(viewModel);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Models.Login model)
        {
            var user = _context.User.FirstOrDefault(u => u.Email == model.Email && u.Password == model.Password);
            if (user != null)
            {
                
                HttpContext.Session.SetString("Id", user.ID.ToString());
                return RedirectToAction("DashBoard", user);
            }
            else
            {
                
                // Помилка: невірний електронний лист або пароль
                ModelState.AddModelError(string.Empty, "Невірний електронний лист або пароль");
                return View();

            }
        }
            // GET: Users
            public async Task<IActionResult> Index()
        {
            return View();

        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                if (user.Password != user.repeatPassword)
                {
                    ModelState.AddModelError("RepeatPassword", "Паролі не співпадають");
                    return View(user);
                }
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login)) ;
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName,Email,Password")] User user)
        {
            if (id != user.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.User == null)
            {
                return Problem("Entity set 'server2MVCContext.User'  is null.");
            }
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.User?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}
 

server2MVC/server2MVC/Views/Home/Index.cshtml
@model IEnumerable<server2MVC.Models.Advertismnet>

@{
    ViewData["Title"] = "Ternopil Lost&Found";
   
}
    <div class="header">
    <div class="headerWrapper">
        <div class="headerLogo"">
            <img src="/Image/logo.svg" alt="logo" />
            <p>Ternopil Lost&found</p>
        </div>
        <div class="registrBtn">
            <a asp-controller="Advertismnets" asp-action="Create"> <button class="addOgl">Додати оголошення</button></a>
            <div style='display:flex'>
            @{
                bool isLoggedIn = ViewBag.IsLoggedIn ?? false;
                if (!isLoggedIn)
                {
                       <a asp-controller="Users" asp-action="Login"><button class="signIn">Вхід</button></a>
                       <a asp-controller="Users" asp-action="Create"><button class="SignUp">Реєстрація аккаунту</button></a>
                
                }
                if (isLoggedIn)
                {
                        <div class="popupConteiner" >
                            <img src="/Image/user-icon.svg">
                            <div class="popup">
                                 
                                <a asp-controller="Users" asp-action="DashBoard">Особистий кабінет</a>
                                <a asp-controller="Users" asp-action="Logout">Вихід</a>
                                
                            </div>
                        </div>

                            }
            }
                
            </div>
        </div>
        </div>

    </div>
    <div class="MaiWwrapper">
        <div class="logo"><img src="/Image/logo.svg" alt="logo" /></div>
        <div class="Text">
            <h1>Ternopil lost&found</h1>
            <p>Сайт " Тернопіль Лост&Фаунд"  служить як централізований ресурс для мешканців Тернополя та околиць, які втратили або знайшли особисті речі.</p>
            <a asp-controller="Advertismnets" asp-action="Create"><button class="MainAddOgl">Додати оголошення</button></a>
        </div>
    </div>
    <div class="FullAnnouncementWrapper">
        <h1>Оголошення</h1>
        <div class="announcementWrapper">

        @foreach (var item in Model.Take(8))
        {
            
                <div class="announcement">
                <div class="category-label category-@(item.category.ToLower())">
                    @item.category
                </div>
                <div class="announcementImg">
                    <img src="@Url.Content(item.ImagePath)" alt="foto" />
                </div>
                <div class="announcementText">
                    <div class="title"><h3>@Html.DisplayFor(modelItem => item.Title)</h3></div>
                    <div class="text">
                        <p>@Html.DisplayFor(modelItem => item.Description)</p>

                    </div>
                    <div class="phone"><p>@Html.DisplayFor(modelItem => item.phoneNum)</p></div>
                    <button class="details-button">Details</button>
                </div>
                

            </div>
                                      
        }
        <div id="announcementModal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <div class="modal-body">
                    <div class="modal-image"><img src="" alt="foto"></div>
                    <div class="modal-info">
                        
                        <div class="modal-title"><h3></h3></div>
                        
                            <div class="modal-category"><span>Категорія:</span> <p></p></div>
                        
                        <div class="modal-description"> <span>Опис:</span> <p></p></div>
                     
                        
                        <div class="modal-phone"><span>Номер телофону:</span> <p></p></div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <a style=" margin-top:20px" asp-controller="Advertismnets" asp-action="Advertiements"><button class="addOgl">Усі оголошення</button></a>
    </div>
    <div class="FooterWrapper">
        <div class="imgContainer">
            <img src="/Image/light_logo.svg" alt="logo" />
        </div>
        <div class="AboutUs">
            <h2>Ternopil lost&found</h2>
            <p>Про нас</p>
            <p>Політика конфіденційності</p>
        </div>
        <div class="Contacts">
            <div class="ContactsText"><p>Наші контакти</p></div>
            <div class="phone">
                <p>Телефон</p>
                <p>+380975461223</p>
            </div>
            <hr />
            <div class="email">
                <p>Пошта</p>
                <p>ternopilLostFound@gmail.com</p>
            </div>
            <hr />
        </div>

    </div>
<script src="~/js/site.js"></script>